import Link from "next/link";
import { getCurrentBrand } from "../../lib/api";

export default async function TermsPage() {
  const brand = await getCurrentBrand();

  return (
    <article>
      <p className="section-label">
        <Link href="/">&larr; Latest</Link>
      </p>

      <div className="article-header">
        <h1 className="article-title">Terms of Use</h1>
        <p className="article-dek">
          Template legal content for {brand.name} — see the notice below before relying on it.
        </p>
      </div>

      <div className="legal-body">
        <p>
          <strong>This is placeholder legal content, not legal advice.</strong> It was drafted to give this
          site a reasonable starting structure, not reviewed by an attorney, and not tailored to your
          jurisdiction, entity, or actual data practices. Have it reviewed by a qualified lawyer before
          relying on it for a real, public-facing product.
        </p>

        <h2>1. What this site is</h2>
        <p>
          {brand.name} is a news aggregator. Most articles are short, automatically curated briefs summarizing
          coverage from third-party publishers, with a link to the original source. Articles marked as such are
          written by {brand.name} staff; everything else is sourced from and attributed to the outlet named on
          the article.
        </p>

        <h2>2. Third-party content and links</h2>
        <p>
          Article briefs excerpt and summarize reporting that remains the property of its original publisher.
          {" " + brand.name} does not claim ownership over third-party content and is not responsible for the
          accuracy, availability, or content of any external site you reach by following a "read the full
          story" link. You leave this site at your own risk.
        </p>

        <h2>3. No warranty</h2>
        <p>
          This site and its content are provided "as is," without warranties of any kind, express or implied,
          including accuracy, timeliness, or fitness for a particular purpose. News summaries are generated by
          an automated process and may contain errors.
        </p>

        <h2>4. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, {brand.name} and its operators are not liable for any
          indirect, incidental, or consequential damages arising from your use of this site or reliance on its
          content.
        </p>

        <h2>5. Notifications</h2>
        <p>
          If you opt in to browser notifications, you'll receive alerts about new articles only while this site
          is open in your browser and only for as long as your browser's notification permission remains
          granted. You can revoke this at any time in your browser's site settings.
        </p>

        <h2>6. Changes</h2>
        <p>
          These terms may be updated at any time without prior notice. Continued use of the site after a change
          constitutes acceptance of the revised terms.
        </p>

        <p>
          Questions about these terms? See the <Link href="/privacy">Privacy Policy</Link> for how we handle
          data, or contact the site operator directly.
        </p>
      </div>
    </article>
  );
}
